### ISSUE TITLE
7.0.5 breaks logging when launched as a cronjob

### ISSUE THREAD

**Issue by brainsys** [nanos/FediFetcher#119]
Thank you for adding logging options in 7.0.5.

It works as expected when FedFetcher is run as a bash job on Debian 11. The same options (or none) do not produce logs when run from a crontab. The paths are all absolute and the same job ran successfully on 7.0.4. I suspect there may be a now be a relative link within FediFetcher.

**Comment by nanos** [comment]
Hm, I cannot reproduce this. Personally I do run FediFetcher as a cronjob, and I do continue to get my logs.

Can you please share your crontab setup, as well as your FediFetcher config?

**Comment by nanos** [comment]
Hm. There is nothing in that script that would lead to output being saved to the disk. 

The behaviour of the offer hasn’t changed in that log output goes to stdout. So you’d need to redirect it to the log file.

**Comment by nanos** [comment]
closing this now as stale. feel free to re-open if this is still an issue
