### ISSUE TITLE
blocks and run FediFetcher as Admin

### ISSUE THREAD

**Issue by Tealk** [nanos/FediFetcher#121]
Hello,

because it was just asked in the chat and I'm not quite sure, how does FediFetcher actually deal with blocking at user level if you install the tool as admin?

**Comment by colinstu12** [comment]
Do you mean what FediFetcher does when you block other users? Or if other users have blocked you?

**Comment by nanos** [comment]
I’m not sure what chat you are referring to, but in short: FediFetcher acts like search. There is no magic about it. It’s between the two instances to figure out what should be blocked and what should be displayed, and the specifics will probably depend on both the software of your server and of the remote server. Fedifetcher doesn’t and cannot impact this.

**Comment by Tealk** [comment]
Ok, thanks for the answer. So you can't bypass blocks with the fetcher.

@colinstu12 My zenario would have been the following:
User1@instance1 blocks user2@instance2, but now instance2 uses the FediFetcher in the admin context and then it would have been possible to bypass the block via this context.

**Comment by colinstu12** [comment]
Admins (or any user) can't magically bypass blocks (if the block is against them). You will see Error 403s when you try to hit links that are attempting to be fetched (both when manually trying to load that link via masto web UI, or in the fedifetcher logs too). I first discovered / reported this in #101 . 
If there's another user on your instance that isn't blocked by this person, and they're following them / whatever that is triggering the attempt to pull in these context links, then it could at least retrieve them for your instance, but that content would still be hidden for that user that has been blocked by the other.

**Comment by Tealk** [comment]
thank you for the detailed explanations, for me the issue is now closed.
