### ISSUE TITLE
Implement more detailed UA

### ISSUE THREAD

**Issue by nanos** [nanos/FediFetcher#122]
This is because FediFetcher is apparently [responsible for very high load on at least some instances](https://chaos.social/@leah/112672275881822072), and this would allow some level of more granular blocking

**Comment by p37307** [comment]
That's a great addition. Nice job.

**Comment by colinstu12** [comment]
Is there any way to fedifetcher to keep track of previously queried/retrieved statuses? It seems to check for the same stuff over and over, even if the context has already been retrieved. Not sure if this causes a real bad impact or not on instances but if there's any way to make it less needlessly chatty seems like it would be preferable.

**Comment by nanos** [comment]
> It seems to check for the same stuff over and over, even if the context has already been retrieved. 

Context may change (ie more replies added) so it’s expected to re-check context. 

But maybe we can do something to slow this down. I’ll think about this a bit more and open an issue for discussion
