### ISSUE TITLE
Add custom extension to robots.txt cache

### ISSUE THREAD

**Issue by p37307** [nanos/FediFetcher#135]
Because of the domain names extension, my OS is associating filetypes to the cached robots files in artifacts.

For instance, it associates domains ending in .au as audio files, .one as MS Office OneNote files, .cat as Windows security cat files, .com as MS_DOS applications, etc.

It may not be a big deal unless my search indexer tries to read its data, expecting to get data associated with those filetypes and mucks up.

Could you add a unique extension when it saves the robots file that is universally recognized as a text file.

![image](https://github.com/nanos/FediFetcher/assets/22573401/e1f67f8c-828b-47fa-965c-cf1a52c864c5)

![image](https://github.com/nanos/FediFetcher/assets/22573401/295a9d06-b414-4484-89c3-3b5cbbedda7d)

![image](https://github.com/nanos/FediFetcher/assets/22573401/5519927d-8e61-4a71-910b-0e806e1c31c0)

**Comment by nanos** [comment]
Oops. I do realise that this is probably not the smartest anyway. I’m sure bad stuff will happen if someone has utf-8 glyphs in their domain name. I think I’ll just do a hash of the domain name and use that…
