### ISSUE TITLE
Job failed: 'dict' object is not callable

### ISSUE THREAD

**Issue by p37307** [nanos/FediFetcher#136]
Initial, manual run of 7.1.3.

It was churning along and then,

```
2024-06-28 14:26:56.334 Eastern Daylight Time: Job failed after 2:09:01.502360.
Traceback (most recent call last):
  File "REDACTED\find_posts.py", line 1585, in <module>
    add_user_posts(arguments.server, token, filter_known_users(mentioned_users, all_known_users), recently_checked_users, all_known_users, seen_urls, seen_hosts)
  File "REDACTED\find_posts.py", line 281, in filter_known_users
    return list(filter(
TypeError: 'dict' object is not callable
```

config
 ```
 "home-timeline-length": 20,
  "max-followings": 20,
  "max-bookmarks": 150,
  "http-timeout": 10,
  "from-notifications": 1,
  "max-favourites": 40,
  "remember-users-for-hours": 24,
  "from-lists": 1,
  "max-list-length": 50,
  "max-list-accounts": 10,
  "max-followers": 80
```

(redacted file path)

Also, I have a large list. It would be nice to blacklist a particular from running. I know you have a lot on your plate and doing a great job.

**Comment by nanos** [comment]
huh. how strange is that! I'm pretty sure I haven't touched this in ages 🤔

**Comment by nanos** [comment]
I have literally no idea what's happening here. The same code is running just fine for me.

Are you sure you are on the latest commit, and haven't modified anything locally?

**Comment by nanos** [comment]
Oh, I think I got it now. I think this is another symptom of the bug that caused #134 

Can you update your clone to the latest commit, and hopefully that’ll fix it. 

Let me know please

**Comment by p37307** [comment]
Ok, done and running. As soon as it completes or fails, I will let you know.

**Comment by p37307** [comment]
It seems to have fixed that issue. I ran with list options and can confirm that https://github.com/nanos/FediFetcher/commit/e85384a5a64c3f02720112eb576ce9d740767e58  ran without an error and completed.

**Comment by nanos** [comment]
Great. Thanks for confirming.
