### ISSUE TITLE
getAllRepliesToKnownPosts: All jobs have failed

### ISSUE THREAD

**Issue by Coehill** [nanos/FediFetcher#148]
I set up FediFetcher for Mastodon but am getting this error:

‣ Run python find_posts.py --lock-hours=0 --access-token=*** -c="./config.json" 2024-07-10 15:55:07 UTC: Starting FediFetcher 2024-07-10 15:55:07 UTC: Getting context for home timeline 2024-07-10 15:55:08 UTC: Error getting timeline toots: Error getting URL https://my_domain.com/api/v1/timelines/home. Status code: 401. It looks like your access token is incorrect. 2024-07-10 15:55:08 UTC: Job failed after 0:00:01.044772 Traceback (most recent call last): File "/home/runner/work/FediFetcher/FediFetcher/find_posts.py", line 1667, in <module> timeline_toots = get_timeline(arguments.server, token, arguments.home_timeline_length) File "/home/runner/work/FediFetcher/FediFetcher/find_posts.py", line 362, in get_timeline response get_toots(url, access_token) File "/home/runner/work/FediFetcher/FediFetcher/find_posts.py", line 401, in get_toots raise Exception( Exception: Error getting URL https://my_domain.com/api/v1/timelines/home. Status code: 401. It looks like your access token is incorrect. Error: Process completed with exit code 1.

This is my config.json:
{
  "access-token": "my_access_token",
  "server": "my_server.com",
  "home-timeline-length": 200,
  "max-followings": 80,
  "from-notifications": 1
}

My Mastodon app has these permissions:
read read:accounts
read:favourites
read:follows
read:lists
read:notifications
read:search
read:statuses

**Comment by nanos** [comment]
Here is your error:

> Status code: 401. It looks like your access token is incorrect. 

so yeah, your access token is incorrect. Try to regenerate it and ensure you don’t make any errrors with copy and paste. 

If you are using GitHub actions (which the issue title seems to indicate, please also note this section the readme:

![image](https://github.com/nanos/FediFetcher/assets/5182595/0699adfc-826c-4a97-87e5-7df32c3a9f6c)

**Comment by nanos** [comment]
Yeah, you need to remove this line:

https://github.com/Coehill/FediFetcher/blob/7b0b40fd25329f057f8e42eebc20c5e1b7403831/config.json#L2

as it stands you are providing the access token `ACCESS_TOKEN` rather than your actual access token.

**Comment by nanos** [comment]
I will close this now as there has been no response. Please feel free to re-open if this doesn't resolve the issue.

**Comment by Coehill** [comment]
@nanos Thanks, the action is now running for me. I made a few small edits to the readme since I misinterpreted the instructions.

https://github.com/nanos/FediFetcher/pull/149
