### ISSUE TITLE
Possible performance issues after a recent update

### ISSUE THREAD

**Issue by stefanbohacek** [nanos/FediFetcher#156]
After a recent update (https://github.com/stefanbohacek/FediFetcher/commit/df484696d98626295c8569e8804ad2b597a41da3), the CPU and bandwidth usage of my Mastodon server have increased, see attached screenshot from DigitalOcean.

![A screenshot of three graphs - server bandwidth, CPU usage, and disk I/O. Both bandwidth and CPU usage increased after an update on August 11.](https://github.com/user-attachments/assets/8d113310-20af-4183-87ec-f924b1961ddc)

Here's my `config.json` file:

```json
{
  "server": "stefanbohacek.online",
  "home-timeline-length": 200,
  "max-followings": 80,
  "from-notifications": 1
}
```

I have not made any changes other than fetching the latest code as shown above.

The droplet has 2 virtual CPUs, 4 GB RAM, and a 50 GB SSD.

**Comment by nanos** [comment]
It looks like you have updated from 7.1.1. The only significant change I can think of here, is that in 7.1.2 we introduced improved caching of robots.txt files, which uses sha256 to hash domain names over and over again.

Can you try #157 which uses xxhash instead of sha256 and see if that improves things for you?

(Don't forget to run `pip install -r requirements.txt`)

**Comment by stefanbohacek** [comment]
@nanos Thank you! I should also add that I'm running FediFetcher as a GitHub Action. Either way, I pulled in the latest changes and will keep an eye on the server throughout the day.

**Comment by nanos** [comment]
Ah, in that case this won't make any difference whatsoever. 

If you are running FediFetcher as GH Action, then what server are those graphs from?

**Comment by stefanbohacek** [comment]
Right. So that's from the actual stefanbohacek.online Mastodon server. I haven't made any changes to the server itself, and the time when the graph started to change matches exactly when I pulled in the update, so I figured maybe the frequency of API calls might have changed? Would it be helpful to share any logs perhaps?

**Comment by nanos** [comment]
Oh, I see. 

That, quite frankly, makes no sense whatsoever: Changes since 7.1.1 have only served to reduce the load on the actual mastodon server, rather than increase it, with FediFetcher increasingly making use of caching to avoid repeated requests for the same thing.

As such I'm tempted to conclude that this increase is very likely unrelated. 

Did you see an uptick in Sidekiq jobs?

Did you make any other changes?

**Comment by nanos** [comment]
Hm. Looking through your GH Actions logs, there are a couple of things that stand out to me:

1. Your actions run for a _very_ long time: FediFetcher takes < 1 min most of the time for me, with similar configuration
2. Your `replied_toot_server_ids` file is empty.

I wonder if these two are connected somehow?

**Comment by nanos** [comment]
Is it possible your mastodon server is just busier than usual? More notifications maybe? 

I sometimes get this when I post something popular, and get dozens of likes: My FediFetcher run time explodes as it's backfilling all those profiles, and that of course has a knock-on effect on the mastodon instance.

**Comment by stefanbohacek** [comment]
> Your actions run for a very long time

Good catch! Looking at https://github.com/stefanbohacek/FediFetcher/actions/workflows/get_context.yml?page=17, it is very clear this has to do with the FediFetcher update.

> 9:24: 1m 52s
> 9:35: 1m 50s	
> 9:45: 1m 51s
> 9:47: merged latest changes
> 9:55: 1h 54m 43s
> 10:15: 16m 29s
> 10:35: 8m 26s

> Did you make any other changes?

Nope.

> Is it possible your mastodon server is just busier than usual? More notifications maybe?

Not particularly.

> Did you see an uptick in Sidekiq jobs?

I'll look into this a bit more. I also paused the workflow for now to see if this has any impact.

**Comment by nanos** [comment]
> Good catch! Looking at https://github.com/stefanbohacek/FediFetcher/actions/workflows/get_context.yml?page=17, this strongly hints as having to do with the FediFetcher update.
> 
> > 9:24: 1m 52s
> > 9:35: 1m 50s
> > 9:45: 1m 51s
> > 9:47: merged latest changes
> > 9:55: 1h 54m 43s
> > 10:15: 16m 29s
> > 10:35: 8m 26s

You can't really compare these: The 09:45 one, and all before that error out, so the run time is simply not the run time of a complete run.

I cannot find any previous successful run in your log, so I cannot find a comparison.

I must admit that at the moment I cannot think of any recent changes that could've caused this.

**Comment by nanos** [comment]
Yeah, it doesn’t surprise me to see that it’s called down. With backfilling that many posts it’ll have an impact. 

I’m just not sure why it would backfill that much. In a cursory glance I couldn’t see any obvious duplication, hence asking earlier whether your server was just very busy. 

You could try to turn off `from-notification`, `backfill-with-context`, and/or `backfill-mentioned-users`. These three will be having by far the biggest impact (particularly `backfill-with-context`) but obviously they’ll also mean you’re missing out on some functionality (see the readme for a description of each option). Up to you to decide whether it’s worth doing.

**Comment by stefanbohacek** [comment]
I think I'm going to close this ticket for now. You confirmed that there were no issues with the update, and gave me a few pointers to look at.

And looking at the past FediFetcher runs, I am wondering if it's the other way around, maybe this has always been an issue, but the recent update fixed whatever was causing the workflow to error out.

I will go over the settings and see if I can tweak them better. Thank you, I appreciate all your help!

**Comment by nanos** [comment]
OK, let me know if you need any more guidance at any time, or if you find out anything that would be helpful to share, please 👍
