### ISSUE TITLE
Suggest systemd service example for fedifetcher has user set to something other than root for security purposes

### ISSUE THREAD

**Issue by ethereal-engineer** [nanos/FediFetcher#167]
Currently the systemd service example has
```
User=root
```
I have just noticed this and changed mine to a de-privilaged user that also runs mastodon (`mastodon`).

Probably a good idea to suggest this to others.

**Comment by nanos** [comment]
Thanks. Agree this would be a good idea. Are you able to provide a PR?

**Comment by ethereal-engineer** [comment]
Also, the service should not have an install section, as it is triggered by timer and not meant to be enabled directly.

**Comment by nanos** [comment]
I've changed this in the process of moving this to a wiki #168 : https://github.com/nanos/FediFetcher/wiki/Running-FediFetcher-as-a-systemd-timer

**Comment by ethereal-engineer** [comment]
Oh this is perfect. This security concern had me grepping through all my unit files to see what else doesn't need root. Will use analyze instead. Thanks!
