### ISSUE TITLE
Proposed Windows Task Scheduler documentation

### ISSUE THREAD

**Issue by p37307** [nanos/FediFetcher#170]
Below is my initial draft contribution to the request for Windows Task Scheduler setup info. See https://mstdn.thms.uk/@michael/113107167940813141. Note: There are probably better ways to describe some of these steps, better grammar, etc. 

### Install Python and PIP

FediFetcher requires Python to run. The best way to install Python on Windows is by downloading the official Python installer from the Python website at https://python.org. After the page has finished loading, click Downloads. https://www.python.org/downloads/ The page should detect you are on Windows and suggest a version to download under the title, "Download the latest version for Windows." Some say 32-bit is better than 64-bit since some third-party modules that you may want to use in the future might not install correctly with a 64-bit version of Python.

![image](https://github.com/user-attachments/assets/80304cea-6cbe-4c4b-9c39-f79f8e24e70b)

After the Python installer file has finished downloading, launch it by double-clicking on it in order to begin the installation. Be sure to select, make sure the “**_Add Python to PATH_**” .

![image](https://github.com/user-attachments/assets/5dc5f621-7d44-4f3f-84f4-de837f96266f)

Once install is finished, open the Windows Command Prompt by launching cmd.exe, type pip and hit Return. You should get the generic PIP help dialogs. If it shows an error, go through install processes again and make sure you choose to in Add Python to Path.
![test python](https://github.com/user-attachments/assets/e0bd6ae2-c7d3-4219-bb3c-7a9d01df318a)

### Install FediFetcher on Windows
To install FediFetcher, either download the Zip file or install via PIP.  This guide will assume the FediFetcher install folder is `C:\FediFetcher`.

### Install via zip download
Download Fedifetcher and unzip it to C:\FediFetcher.

### Install via PIP
You will need _Git for Windows_. Install from https://git-scm.com/download/win or https://gitforwindows.org/

After you have installed _Git for Windows_, open the Windows Command prompt  to C:\FediFetcher. Easiest way to do this is open C:\FediFetcher in Windows Explorer and then type CMD in the address bar and hit enter.

Install via GIT: `git clone https://github.com/nanos/FediFetcher`

Run `pip install -r requirements.txt`

To update, follow the version release notes.

### Configure FediFetcher
 Follow the setup instructions for configuring your FediFetcher's config file. https://github.com/nanos/FediFetcher/wiki/FediFetcher-configuration-options

### Initial Run
It's best to run FediFetcher once before you set it up on a schedule. You can run FediFetcher with the following command if you installed it at c:\FediFetcher: `C:\FediFetcher\find_posts.py -c=./artifacts/config.json`

### Setup FediFetcher to run on a schedule via Task Scheduler

1. To set FediFetcher up to run on a schedule, open Task Scheduler by pressing the Windows key and by typing 'Task Scheduler' At some point it should appear in a side box before you finish typing it out. Open Task Scheduler.
2. On the far right, choose 'Create basic task.' You must give your task a name. In the example, I named it FediFetcher. Optional, Enter a description so down the road you know what the task is about. Click next 

![TS basic task](https://github.com/user-attachments/assets/875acbfc-0624-4325-a297-6bf33cab18f7)
![basic task step 1](https://github.com/user-attachments/assets/00d97442-90f2-4dad-a860-622f59786b61)

3. You must set when FediFetcher will run under Trigger. I chose 'When the Computer Starts.' Click Next.

![basic task step 2](https://github.com/user-attachments/assets/52ca8912-dcc7-413f-aee0-69b030ebf97d)

4. Now, choose the Action. Select 'Start a Program.' Click Next.
5. In the Program/script box, put '`C:\FediFetcher\find_posts.py`'. Now add arguments. '`c=./artifacts/config.json`'. It's important to start in "`C:\FediFetcher`" or else Python will use its default folder structures, and your artifacts folder will not be in your FediFetcher folder and it may error out. Now click Next. 

![basic task step 3](https://github.com/user-attachments/assets/8b0db4ea-f69b-400d-8f06-3ce325c3f979)

6. Be sure look at your command and make sure it is correct and then tick "Open the properties dialog" as we need to set how often FediFetcher will run.

![basic task step 4](https://github.com/user-attachments/assets/b18c1b6d-7245-43c6-a23a-02397f11e15d)

7. Now go to the 'Triggers' tab, select 'At Startup' and edit.

![basic task step 5](https://github.com/user-attachments/assets/6027ba1b-eaf2-43a0-9800-9b352316793d)

8. Tick 'Repeat Task Every' and select how often you want it to run. If Fedifetcher is running, it will skip that run.
Next change duration to indefinitely. Click Ok.

![basic task step 6](https://github.com/user-attachments/assets/b90b7456-3dfb-4079-8aa9-357bfaa19fb2)

Now, FediFetcher is setup to run as a scheduled task. You can right click the task to run it now or the next time you restart your computer, it will be set to run on a schedule.

**Comment by nanos** [comment]
Thanks so much @p37307 ! Really appreciate the effort you put into this!

I've made some edits (mainly to shorten it a bit), and put it live here: https://github.com/nanos/FediFetcher/wiki/Running-FediFetcher-as-a-Scheduled-Task-in-Windows

Let me know what you think.

**Comment by p37307** [comment]
You're welcome, @nanos. Glad I could contribute and give back to the project and the FOSS community.
