### ISSUE TITLE
Syntax Error?

### ISSUE THREAD

**Issue by veeyawn** [nanos/FediFetcher#173]
First, thanks for making this. I run a small instance for a few friends and me and looking forward to FediFetcher expanding our Fediverse. 

I've got it all setup and plan on running as a cron job on my Mastodon server. When I attempt to run it manually I'm greeted with a Syntax error: 

 File "find_posts.py", line 59
    notifications = get_paginated_mastodon(f"https://{server}/api/v1/notifications", since, headers={"Authorization": f"Bearer {access_token}",})
                                                                                  ^
SyntaxError: invalid syntax

The pointer is pointing to just after the " after notifications. Any help greatly appreciated.

**Comment by nanos** [comment]
How are you running fedifetcher?

**Comment by AndrewKvalheim** [comment]
Looks like it’s Python 2:

```console
$ NIXPKGS_ALLOW_INSECURE=1 nix-shell --packages 'python2' --run 'python ./find_posts.py'
  File "./find_posts.py", line 59
    notifications = get_paginated_mastodon(f"https://{server}/api/v1/notifications", since, headers={
                                                                                  ^
SyntaxError: invalid syntax
```

FediFetcher is written for Python 3:

https://github.com/nanos/FediFetcher/blob/ca3703149bb91d3b450107f2b5c096090724fe70/find_posts.py#L1

**Comment by nanos** [comment]
if executing `python` launches python 2, try running `python3` instead

**Comment by veeyawn** [comment]
@nanos running it on my Mastodon server which is Debian. Hoping to set it up as a cron job. Ahhhh pyhon2...grrrrr. Thank you! 
you! Working!
