### ISSUE TITLE
ghcr.io image tag for v7.1.7 missing

### ISSUE THREAD

**Issue by b2cc** [nanos/FediFetcher#174]
Can you please add a tag to the v7.1.7 release? It's currently not possible to pull by tag (only via `:latest`):

```
LAST SEEN   TYPE      REASON     OBJECT                           MESSAGE
59s         Warning   Failed     pod/fedifetcher-28755945-d6ptd   Failed to pull image "ghcr.io/nanos/fedifetcher:v7.1.7": reading manifest v7.1.7 in ghcr.io/nanos/fedifetcher: manifest unknown
```

Thanks!

**Comment by nanos** [comment]
ok, this was annoying. Think it's fixed now, and hopefully it will survive the next releases.

You can get v7.1.12 (which is identical to 7.1.7 except for a bit of tidy up and removing unnecessary files)

**Comment by b2cc** [comment]
Thanks for the quick fix!

**Comment by b2cc** [comment]
Thanks for the quick fix!
