### ISSUE TITLE
KeyError for `"reblog"` in toot_has_parseable_url causing failure

### ISSUE THREAD

**Issue by Taywee** [nanos/FediFetcher#179]
```
2024-09-26 17:29:07 UTC: Pulling replies to the last 100 favourites
2024-09-26 17:29:07 UTC: Job failed after 0:06:42.219804.
Traceback (most recent call last):
  File "/app/find_posts.py", line 1729, in <module>
    known_context_urls = get_all_known_context_urls(arguments.server, favourites,parsed_urls, seen_hosts)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/find_posts.py", line 538, in get_all_known_context_urls
    if toot_has_parseable_url(toot, parsed_urls):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/find_posts.py", line 557, in toot_has_parseable_url
    parsed = parse_url(toot["url"] if toot["reblog"] is None else toot["reblog"]["url"],parsed_urls)
                                      ~~~~^^^^^^^^^^
KeyError: 'reblog'
```

I think this may be a badly-behaved server, but it might be worth replacing the `toot["reblog"]` with a `toot.get("reblog")` to handle the field being absent.

**Comment by nanos** [comment]
this is a strange one do you know the server url and post ID by any chance?

**Comment by Taywee** [comment]
It's my Sharkey server, and actually, the output is weird in general, when I trace what the code is trying to do:

```
> curl -H 'Authorization: Bearer ACCESSTOKEN' -H 'Content-Type: application/json' 'https://shark.axfive.net/api/v1/favourites?limit=100'
[{},{}]
```

The number of `{}` in the array corresponds to the number of favorites I have.  They're just all coming back empty for some reason.

Even replacing that with `toot.get('reblog')`, it wouldn't work right.  This looks like a Sharkey bug.  Sorry for the spurious bug report.

**Comment by nanos** [comment]
Ah, are you using FediFetccher against a Sharkey instance? In that case I'm afraid we don't support that. Have a look at this issue: It might contain helpful information for you: #72

**Comment by Taywee** [comment]
Good note, thank you.  I should have mentioned in the first place which server I was using.  I will note that I have my FediFetcher running with lots of default settings, and other than favourites, it runs without a hiccup against Sharkey.
