### ISSUE TITLE
Access Token Incorrect 401 for GitHub actions

### ISSUE THREAD

**Issue by Crazypedia** [nanos/FediFetcher#184]
I've been checking and rechecking the config and permissions assigned to the to app in mastodon, those are right. Saved the access token and verified they match between the one I pasted (and removed the copied return) to the secrets(ACCESS_TOKEN), but I still get this error that the token is invalid. Obviously not going to stick it in the config file, but I don't know how to troubleshoot this.

https://github.com/Crazypedia/FediFetcher/actions/runs/11467209845/job/31909587831
>  python find_posts.py --lock-hours=0 --access-token=*** -c="./config.json"
>   python find_posts.py --lock-hours=0 --access-token=*** -c="./config.json"
>   shell: /usr/bin/bash -e {0}
>   env:
>     pythonLocation: /opt/hostedtoolcache/Python/3.10.15/x64
>     PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.10.15/x64/lib/pkgconfig
>     Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.15/x64
>     Python[2](https://github.com/Crazypedia/FediFetcher/actions/runs/11467050317/job/31909087242#step:7:2)_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.15/x64
>     Python3_ROOT_DIR: /opt/hostedtoolcache/Python/[3](https://github.com/Crazypedia/FediFetcher/actions/runs/11467050317/job/31909087242#step:7:3).10.15/x64
>     LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.15/x6[4](https://github.com/Crazypedia/FediFetcher/actions/runs/11467050317/job/31909087242#step:7:4)/lib
> 2024-10-22 19:21:07 UTC: Starting FediFetcher
> 2024-10-22 19:21:07 UTC: Getting context for home timeline
> 2024-10-22 19:21:07 UTC: Error getting timeline toots: Error getting URL https://pagan.plus/api/v1/timelines/home. Status code: 401. It looks like your access token is incorrect.
> 2024-10-22 19:21:07 UTC: Job failed after 0:00:00.704977.
> Traceback (most recent call last):
>   File "/home/runner/work/FediFetcher/FediFetcher/find_posts.py", line 1699, in <module>
>     timeline_toots = get_timeline(arguments.server, token, arguments.home_timeline_length)
>   File "/home/runner/work/FediFetcher/FediFetcher/find_posts.py", line 366, in get_timeline
>     response = get_toots(url, access_token)
>   File "/home/runner/work/FediFetcher/FediFetcher/find_posts.py", line 40[5](https://github.com/Crazypedia/FediFetcher/actions/runs/11467050317/job/31909087242#step:7:5), in get_toots
>     raise Exception(
> Exception: Error getting URL https://pagan.plus/api/v1/timelines/home. Status code: 401. It looks like your access token is incorrect.
> Error: Process completed with exit code 1.

**Comment by nanos** [comment]
How did you generate the access token?

**Comment by Crazypedia** [comment]
I created an application at https://$MastodonInstance/settings/applications and set the read properties, then copied the token since it changes when you update those.

**Comment by nanos** [comment]
Can you please go in there and click 'Regenerate access token'. Then save the new access token in Action Secret.

**Comment by Crazypedia** [comment]
done that a couple of times, and again just now, same error.

**Comment by nanos** [comment]
A `401` error definitely indicates that the access token is incorrect. Ensure you are entering it without any white space.

Can you show a screenshot of where you have entered the access token in your GitHub repository please?

**Comment by Crazypedia** [comment]
here ya go.

![Screenshot 2024-10-23 16 41 39](https://github.com/user-attachments/assets/795597ca-abd6-4d55-a015-17c5ea8cf9ce)
![Screenshot 2024-10-23 16 38 01](https://github.com/user-attachments/assets/30f0f4da-3d0e-4f9a-a862-984e453c9727)

**Comment by Crazypedia** [comment]
tried making a whole new application in the mastodon interface in case there was something funky with that one, same result =/

**Comment by Crazypedia** [comment]
ok, did a dirty and verified that it worked when the access token was put in the config file. Success! *rotate key

Found a duplicate "access token" variable in the environment settings in addition to the secrets, so I deleted all of them and then remade just the one access token.  it appears to be working now. Problem was likely a misconfiguration in the environment config.

**Comment by nanos** [comment]
Ah, I'm glad you got it sorted. Yes, the duplicate environment variable would have caused this.

Hope you have rotated the access token after removing it from the config.json, as - and you may already know that - the history of that file is public.
