### ISSUE TITLE
List of Access-Token

### ISSUE THREAD

**Issue by RJGhugo** [nanos/FediFetcher#186]
FediFetcher does not skip delete accounts/access-token. It is crashing instead.

`          containers:`
`          - name: fedifetcher`
`            image: ghcr.io/nanos/fedifetcher:latest`
`            args:`
`              - --server=social.g2od.ch`
`              - --access-token=1111...`
`              - --access-token=2222...`
`              - --access-token=3333...`
`#              - --access-token=4444...`
`              - --access-token=5555....`
`              - --home-timeline-length`
`              - "200"`
`              - --max-bookmarks`
`              - "80"`
`              - --max-favourites`
`              - "40"`
`              - --max-followings`
`              - "800"`
`              - --max-followers`
`              - "800"`
`              - --from-notification`
`              - "4"`

**Comment by nanos** [comment]
When you say 'crashing' what do you mean? any error messages?

**Comment by RJGhugo** [comment]
I just saw that FediFetcher crashed.

Just commented out the no more existing **access-token**...

**Comment by RJGhugo** [comment]
Probably you can reproduce it with a "non existing" access-token.

**Comment by nanos** [comment]
Without an error message I'm afraid I cannot advise.

I'm assuming you are using docker? I don't have a docker test environment to reproduce, so would need more info please.

**Comment by RJGhugo** [comment]
`kubectl logs fedifetcher-28885862-6nd49`

`2024-12-02 15:14:44 UTC: Error getting timeline toots: Error getting URL https://social.XXXXXXXX.ch/api/v1/timelines/home.` `Status code: 401. It looks like your access token is incorrect.`
`2024-12-02 15:14:44 UTC: Job failed after 0:03:37.714554.`
`Traceback (most recent call last):`
`  File "/app/find_posts.py", line 1695, in <module>`
`    timeline_toots = get_timeline(arguments.server, token, arguments.home_timeline_length)`
`                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
`  File "/app/find_posts.py", line 362, in get_timeline`
`    response = get_toots(url, access_token)`
`               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
`  File "/app/find_posts.py", line 401, in get_toots`
`    raise Exception(`
`Exception: Error getting URL https://social.XXXXXXXX.ch/api/v1/timelines/home. Status code: 401. It looks like your access token is incorrect.`

**Comment by nanos** [comment]
> Status code: 401. It looks like your access token is incorrect.

It does look like one of the access tokens you have provided is incorrect (maybe revoked, maybe rotated, maybe copy-pasted incorrectly).

My advice: Remove them one by one until you've found the faulty one. To speed up your testing, run it as follows for the test:

```
         - name: fedifetcher
            image: ghcr.io/nanos/fedifetcher:latest
            args:
              - --server=social.g2od.ch
              - --access-token=1111...
              - --home-timeline-length
              - "1"
```

Remove all the other options for testing so you aren't wasting too much time.

**Comment by colinstu12** [comment]
If more than one token is provided and one of them is bad, could Fedifetcher output which token was being used at that time / which one is bad specifically (or at least list first 6 digits of it or something)? Such feature may help with future troubleshooting. I am not a developer sadly so I’m not sure programmatically what would be required, but it SOUNDS feasible? Anyway just an idea. Appreciate all your work.

**Comment by RJGhugo** [comment]
Thanks.

Yes, an **access token** was revoked.

It would be nice to get a waring, instead of an error. Would this be possible?

Further, I have to document the acces-tokens better:

`# user 1`
`- --access-token=1111`
`# user 2`
`- --access-token=2222`

**Comment by nanos** [comment]
Thanks for that.

> It would be nice to get a waring, instead of an error. Would this be possible?

@RJGhugo Possible, yes, but I don't want to do that: I consider an incorrect token an error: The script simply cannot proceed, and a warning would mean that I don't get alerted if the script fails in my own use.

> could Fedifetcher output which token was being used at that time / which one is bad specifically (or at least list first 6 digits of it or something)?

@colinstu12 I will be implementing this. Thanks for the suggestion.

**Comment by RJGhugo** [comment]
Thanks.

**Comment by RJGhugo** [comment]
Thank you for your explanations!
