### ISSUE TITLE
Error 403 when running FediFetcher from same VPS and mastodon server

### ISSUE THREAD

**Issue by danielcolquitt** [nanos/FediFetcher#190]
When I attempt to run FediFetcher from the same VPS that is hosting my mastodon instance, I receive the following fatal error:

`Exception: Error getting URL https://<FQDN>/api/v1/lists with token pq0dN*********************************OQIy0. Status code: 403 
Make sure you have enabled the required scope(s) for your token.`

I have checked and the token is valid and has the appropriate scopes. I have successfully run FediFetcher against the same instance from a different machine (with the same token). The logs for `access.log`, `error.log`,  and `mastodon-web` do not show anything relevant.

**Comment by danielcolquitt** [comment]
`<user>@<host>:/opt/FediFetcher$ /opt/fedifetcher/bin/python3 find_posts.py -c=artifacts/config.json
2024-12-10 16:31:32 UTC: Starting FediFetcher v7.1.14
2024-12-10 16:31:34 UTC: Getting robots.txt file from cache for https://<FQDN>/robots.txt.
2024-12-10 16:31:34 UTC: Job failed after 0:00:02.305859.
Traceback (most recent call last):
  File "/opt/FediFetcher/find_posts.py", line 1651, in <module>
    lists = get_user_lists(arguments.server, token)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/FediFetcher/find_posts.py", line 1391, in get_user_lists
    return get_paginated_mastodon(f"https://{server}/api/v1/lists", 99, {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/FediFetcher/find_posts.py", line 1013, in get_paginated_mastodon
    report_mastodon_error(
  File "/opt/FediFetcher/find_posts.py", line 1452, in report_mastodon_error
    raise Exception(
Exception: Error getting URL https://<FQDN>/api/v1/lists with token pq0dN*********************************OQIy0. Status code: 403 
Make sure you have enabled the required scope(s) for your token.`

**Comment by nanos** [comment]
Please ensure you add the `read:lists` permission to your access token. Then re-generate the token, and supply the new token to FediFetcher.

For more info on which tokens are required see see https://github.com/nanos/FediFetcher/wiki/Access-Token-Scopes

**Comment by danielcolquitt** [comment]
> Please ensure you add the `read:lists` permission to your access token. Then re-generate the token, and supply the new token to FediFetcher.
> 
> For more info on which scopes are required see see https://github.com/nanos/FediFetcher/wiki/Access-Token-Scopes

![Screenshot 2024-12-10 at 16 35 39](https://github.com/user-attachments/assets/8e56b972-3e8c-4ca3-9670-a3de0b5ebeca)

Done - no change - same error. As I said in my opening post, I am running the same version of FediFetcher, using the same access token and `config.json` on a different machine, so it is unlikely to be a token / permissions issue. Could it be something to do with mastodon not allowing API calls from the same machine that runs the instance? (Just a guess - I don't know if this is true).

I am running vanilla Mastodon v4.3.1 on a VPS with Ubuntu 24.04.

**Comment by nanos** [comment]
> Could it be something to do with mastodon not allowing API calls from the same machine that runs the instance?

No. Unless you got something in front of Mastodon that gives a `403`. Do you run mastodon behind CloudFlare or something?

>  so it is unlikely to be a token / permissions issue

A `403` really means one of two things:

 1. If you are connecting directly to Mastodon, then it means that the token doesn't have the required scopes. This could be because of copy and paste errors, or it could be because the token hasn't been re-generated since  changes have been made. (Or because the scope simply hasn't been added, but I take your word that this isn't the case here.)
 2. The only other possible reason for this is that something between FediFetcher and Mastodon (such as CloudFlare, nginx or another proxy) is returning the `403` before it ever reaches Mastodon.

**Comment by nanos** [comment]
One thing that might help you find the source of this, if you are convinced that the token and scopes are correct, is to open up the file `find_posts.py`, and navigate to line 1012 and add these two lines:

```
index 7552934..a7dfaed 100644
--- a/find_posts.py
+++ b/find_posts.py
@@ -1010,6 +1010,8 @@ def get_paginated_mastodon(url, max, headers = {}, timeout = 0, max_tries = 5):
     response = get(furl, headers, timeout, max_tries)
 
     if response.status_code != 200:
+        logger.debug(response.text)
+        logger.debug(response.headers)
         report_mastodon_error(
             f"Error getting URL {url}",
             response.status_code,
```

This will print out the response text and headers above the error message.

**Comment by danielcolquitt** [comment]
After some digging, it looks like CloudFlare's Bot Fight Mode was blocking mastodon queries (and not just FediFetcher). Apologies for overlooking something rather obvious!
