### ISSUE TITLE
Error can't find release

### ISSUE THREAD

**Issue by quicoto** [nanos/FediFetcher#25]
I get quite some errors like this one https://github.com/quicoto/mastodon-get-replies/actions/runs/4491658020/jobs/7900426746

Not sure if there's something we can do about it

Thank you

**Comment by nanos** [comment]
Yeah, that one is seriously annoying. 

I’m considering using a while loop to retry this until it succeeds.

**Comment by nanos** [comment]
Let's have a look how this works with v4.1.3.

Can you update this issue with some feedback in a few days time please? I no longer use the workflow myself, so can't really test it myself.

**Comment by nanos** [comment]
This still seems to happen a fair bit.

@shiruken has contributed #26 which I hope will fix this once and for all.

**Comment by quicoto** [comment]
Quite green from my side so far

https://github.com/quicoto/mastodon-get-replies/actions
