### ISSUE TITLE
TIP when scheduling on Windows via Task Scheduler. 

### ISSUE THREAD

**Issue by p37307** [nanos/FediFetcher#27]
If you copy and rename the script to the .pyw extension instead of the py, you can set it up in Windows Task Scheduler and it will run silent, without opening a console window, unlike regular . py files. Windows will use PYTHONW. EXE instead of PYTHON. EXE.

**Comment by nanos** [comment]
Interesting. I didn't know this. Are you able to file a PR?

**Comment by p37307** [comment]
I've never done a PR before and will need to review how to do it.

**Comment by nanos** [comment]
OK, that's fine. I'll have a look at adding this to the README.

**Comment by nanos** [comment]
@p37307 I've just added a sentence. Can you check that is correct? I'm not familiar with Windows, so would appreciate confirmation.

**Comment by p37307** [comment]
Yes, that looks fine. The only other thing, that could be mentioned, is the .pyw file can be used anytime you want the script to run windowless, not just in Task Scheduler. I don't know why in my original post I tied it so strongly to task scheduler.

**Comment by nanos** [comment]
Great. Thanks @p37307
