### ISSUE TITLE
`cron` schedule variable

### ISSUE THREAD

**Issue by boogah** [nanos/FediFetcher#28]
Would you consider adding an environment variable for the `cron` schedule?

It'd be nice to have the option to run the workflow every 15 or 20 minutes instead of every 10.

**Comment by nanos** [comment]
Thanks for the suggestion @boogah 

I assume you are referring to the GitHub Action?

I'm not sure if it's even possible to do this, to be honest. But even if it was, I'm not sure I'd want to do that: FediFetcher already has a lot of configuration options, to the point of being potentially overwhelming.

If you wanted to adjust the schedule of the cron job you could simply adjust line 7 in the workflow file, which I see you have already done.
