### ISSUE TITLE
Parse error for "toots" from non-Mastodon fediverse applications

### ISSUE THREAD

**Issue by b2cc** [nanos/FediFetcher#30]
While running FediFetcher we see the following error when it tries to parse URLs which are not specific to Mastodon, e.g. PixelFed:
```
2023-03-29 18:58:56.773641 CEST: Error parsing toot URL https://pixelfed.de/p/kaffeeringe/545560350894759521
```

Running with docker image from `latest` tag from timestamp as logged above.

PS: I'm not sure if this tool is meant to be used for Mastodon-to-Mastodon communication specifically. If so please close this issue.

**Comment by nanos** [comment]
Hm. that's very interesting: According to the documentation Pixelfed is supposed to implement the Mastodon API: https://docs.pixelfed.org/technical-documentation/api/

As such we should be able to pull in context for Pixelfed posts.

However, I cannot get this to work, e.g.

```
curl -I https://pixelfed.de/api/v1/statuses/545560350894759521                                                                                                       
HTTP/2 302
cache-control: no-cache, private
content-type: text/html; charset=UTF-8
date: Thu, 30 Mar 2023 06:05:54 GMT
location: https://pixelfed.de/login
server: Apache/2.4.51 (Debian)
```

I'll have too look into this a bit more 🤔

**Comment by nanos** [comment]
This has been confirmed as pixelfed bug: https://mastodon.social/@dansup/110113759189806437

when that bug is resolved we’ll be able to implement this on our end as well.

**Comment by b2cc** [comment]
@nanos : Thanks for the quick investigation!
