### ISSUE TITLE
Something changed and now takes ages to finish

### ISSUE THREAD

**Issue by quicoto** [nanos/FediFetcher#31]
Something changed like an hour ago and now the action runs for more than hour without end. I did cancel the run and attempt to fire it again, but it always gets fetching to no end.

https://github.com/quicoto/mastodon-get-replies/actions

https://github.com/quicoto/mastodon-get-replies/actions/runs/4573577685

**Comment by quicoto** [comment]
@nanos Did you remove commits from your branch?

Now mine has 7 commits that you don't have 😕 

https://github.com/quicoto/mastodon-get-replies

**Comment by nanos** [comment]
yes, I did. apologies. you'll need to re-set your fork

**Comment by mattlehrer** [comment]
How to reset your fork:
https://gist.github.com/dakoctba/7676845

**Comment by quicoto** [comment]
Thanks I just rebased
