### ISSUE TITLE
Process keeps failing

### ISSUE THREAD

**Issue by edoswald** [nanos/FediFetcher#33]
I thought deleting my fork and reforking would fix this.. but the process keeps failing. Here's what's happening right before it fails

2023-04-03 04:32:11.770488 UTC: Added 281 new context toots (with 2 failures)
2023-04-03 04:32:11.770497 UTC: Getting posts from last 80 followings
2023-04-03 04:32:11.917412 UTC: Job failed after 0:04:54.898183.
Error: Process completed with exit code 1.

**Comment by nanos** [comment]
Hi @edoswald .

It does look like GitHub has messed up your log there. No idea why that would be.

But the actual error message is actually several lines above that:

```
Exception: Error getting URL https://wxcloud.social/api/v1/accounts/verify_credentials. Status code: 403
```

[According to the docs](https://docs.joinmastodon.org/methods/accounts/#verify_credentials), this error means 'Your user account is currently disabled, missing a confirmed email address, or pending approval.' Does any of these apply to your account?

**Comment by edoswald** [comment]
Looks like it was what wikiyu mentioned.. running it now to see. Some permissions were missing.
