### ISSUE TITLE
Docker image name is invalid

### ISSUE THREAD

**Issue by AndrewKvalheim** [nanos/FediFetcher#34]
The [example Docker commands](https://github.com/nanos/FediFetcher/blob/e40a5447ee1247756d1facd454ccdf0238933417/README.md?plain=1#L68-L69) fail with the [new name](https://github.com/nanos/FediFetcher/commit/a8cf5d3eef87bf820cf9d5cb9884b18155260c9b):

```console
$ docker --version
Docker version 20.10.21, build v20.10.21
$ docker pull ghcr.io/nanos/FediFetcher:latest
invalid reference format: repository name must be lowercase
```

**Comment by nanos** [comment]
Thanks @AndrewKvalheim ! That's now fixed.
