### ISSUE TITLE
Unclear how to disable backfill

### ISSUE THREAD

**Issue by AndrewKvalheim** [nanos/FediFetcher#37]
The [`--backfill` options](https://github.com/nanos/FediFetcher/blob/b9d82dc07317164b05fd89ee48aeccf4bcc5a580/find_posts.py#L29-L30) are confusing to disable. The documentation [suggests](https://github.com/nanos/FediFetcher/blob/b9d82dc07317164b05fd89ee48aeccf4bcc5a580/README.md?plain=1#L112-L113) setting them to `"0"`, but actually that [enables](https://docs.python.org/3/library/argparse.html#type) them:

> The `bool()` function is not recommended as a type converter. All it does is convert empty strings to `False` and non-empty strings to `True`. This is usually not what is desired.

**Comment by nanos** [comment]
Thanks @AndrewKvalheim

This is now fixed in https://github.com/nanos/FediFetcher/releases/tag/v4.1.10

**Comment by joellimberg** [comment]
Sorry for the horrible format of this report, but I think the above fix actually broke something else; I'm seeing this:

(`NameError: name 'timeline_toots' is not defined`)

![image](https://user-images.githubusercontent.com/875872/230313832-454e3197-fb0b-477c-97dd-bfaf16c887eb.jpeg)
