### ISSUE TITLE
[question] fetching replies for all users on instance?

### ISSUE THREAD

**Issue by Wurzelmann** [nanos/FediFetcher#39]
I read all the instructions and your blog page about it, but I am not sure I understood its functionality correctly, I'm afraid.

I am the admin of a small Mastodon instance (10 users) and I want to use your script to fetch replies for all my users. Is this possible or am I fetching only person A's replies when using person A's access token? And if so, is there a way to do this for my whole instance?

Thank you in advance!

**Comment by nanos** [comment]
No, unfortunately FediFetcher  cannot do this. 

In mastodon you can only get a user’s timeline with an auth token for the user. 

There isn’t really any way around that, other than through accessing the database directly, or through changes in mastodon’s code.

**Comment by Wurzelmann** [comment]
Okay, I see, thank you for clarifying!

**Comment by nanos** [comment]
@Wurzelmann Depending on your users, and your relationship with them, the newly released multi-user support may help you.

It would require your users to send you access tokens, though:

https://blog.thms.uk/2023/04/muli-user-support-for-fedifetcher

**Comment by Wurzelmann** [comment]
Perfect, thank you!
