### ISSUE TITLE
Can I make it do less?

### ISSUE THREAD

**Issue by quicoto** [nanos/FediFetcher#41]
The GitHub actions take too long and they get cancelled over and over https://github.com/quicoto/mastodon-get-replies/actions

I've set HOME_TIMELINE_LENGTH to 10 but that doesn't help either.

Is there a config I can use to fetch less stuff? At the beginning it used to work just fine. Can I skip profile fetching? I'm mainly interested in threads

Thank you

**Comment by nanos** [comment]
Alternatively you might want to try just disabling `BACKFILL_WITH_CONTEXT` which should speed up the process a lot as well.

**Comment by quicoto** [comment]
Thank you for the fast reply, @nanos !
