### ISSUE TITLE
Favourites and Reblogs

### ISSUE THREAD

**Issue by EddiesTech** [nanos/FediFetcher#42]
As mentioned: https://elk.zone/coldrick.me.uk/@eddie/110273363273834774

Would be great to also fetch favourites and reblogs, if possible with the API :)

**Comment by nanos** [comment]
Thanks for the suggestion @EddiesTech 

Favourites should be very straightforward. I can't find a way to get reblogs through the api. Only thing we could theoretically do is fetch all your posts, and then filter by reblogs. But that seems like a lot of effort for very little gain.

I'd suggest you instead favourite and reblog. That way the favouriting should ensure we fetch context

**Comment by nanos** [comment]
This is now implemented:

https://github.com/nanos/FediFetcher/releases/tag/v4.2.1
