### ISSUE TITLE
Exit code 127 with on-fail specified

### ISSUE THREAD

**Issue by jaytay79** [nanos/FediFetcher#46]
I added ON_FAIL and ON_DONE environment variables to my Actions but now I'm getting an error with "command not found", it seems that on-start also needs to be specified? It's also highlighting an issue with max-bookmarks too (note that the URLs have been redacted):

```
Run python find_posts.py --lock-hours=0 --access-token=*** --server=social.racf.guru --reply-interval-in-hours=0 --home-timeline-length=200 --max-followings=80 --user= --max-followers=0  --http-timeout=5 --max-follow-requests=0 --on-fail=https://uptime.zzz/api/push/xxxxxx?status=down&msg=Failed%20Run&ping= --on-start= --on-done=https://uptime.zzz/api/push/xxxxxx?status=ok&msg=OK&ping= --max-bookmarks=0 --remember-users-for-hours=168 --from-notifications=1 --backfill-with-context=1  --backfill-mentioned-users=1  --max-favourites=0
/home/runner/work/_temp/23caf967-1fa7-49dd-965b-7234c27c4927.sh: line 1: --on-start=: command not found
/home/runner/work/_temp/23caf967-1fa7-49dd-965b-7234c27c4927.sh: line 1: --max-bookmarks=0: command not found
Error: Process completed with exit code 127.
```

**Comment by nanos** [comment]
That had me stumped for a while, until I realised that the bug isn't produced by FediFetcher at all, instead it's caused by your bash script.

The reason being the `&` sign, which your bash interprets as starting a new command called `--on-start=:`, which obviously doesn't exist.

You should wrap your callback URLs in quotes:

```
find_posts.py --on-fail="https://uptime.zzz/api/push/xxxxxx?status=down&msg=Failed%20Run&ping="
```

**Comment by nanos** [comment]
Can you update your fork and try again please? Please let me know if that fixes it.

**Comment by jaytay79** [comment]
That looks better, thanks for the quick fix!

**Comment by nanos** [comment]
Thanks for the confirmation!
