### ISSUE TITLE
FR: Allow configuring the access token in a more secure way

### ISSUE THREAD

**Issue by delroth** [nanos/FediFetcher#48]
As far as I can tell from the documentation, the `--access-token` flag is the only way the (required) access token can be passed to FediFetcher. Command lines are usually world readable on Linux systems (via /proc, unless hidepid is in use), and cron/systemd configurations are also often world readable.

Providing an alternative such as e.g. `--access-token-file` being a path to a file that contains the access token would allow deploying fedifetcher on a shared box without leaking tokens to all other residents.

Thank you!

**Comment by nanos** [comment]
Yes, I like the idea. I had actually planned to allow passing a configuration file (which would likely be JSON) where all configuration options can be set, so that one doesn't need to supply a million command line flags.

**Comment by nanos** [comment]
@delroth  You can now use the `--config` flag to provide your configuration options (including the access token) through a file

See https://github.com/nanos/FediFetcher/releases/tag/v4.3.0 for details

**Comment by delroth** [comment]
Thank you!
