### ISSUE TITLE
Migrated to config.json but fails

### ISSUE THREAD

**Issue by quicoto** [nanos/FediFetcher#52]
Hello,

I just migrated to the new JSON configuration

My config file is here https://github.com/quicoto/mastodon-get-replies/blob/main/config.json

Action fails saying the config.json does not exist https://github.com/quicoto/mastodon-get-replies/actions/runs/5277386376/jobs/9545361582

Thank you

**Comment by nanos** [comment]
Fixed in v5.0.1
