### ISSUE TITLE
Fails on exit code 1: not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by SiskoUrso** [nanos/FediFetcher#54]
Since yesterday I have started having an issue with it failing constantly with the error: 

2023-06-18 02:24:18.123189 UTC: Job failed after 0:03:53.352363.
  File "/home/runner/work/FediFetcher/FediFetcher/find_posts.py", line 885, in <module>
    if arguments.backfill_mentioned_users > 0:
TypeError: '>' not supported between instances of 'str' and 'int'
Error: Process completed with exit code 1.

Running as a GitHub action, running the most recent branch 

logs from the last run: https://paste.lanofthedead.xyz/?bc97b25835463f1b#2SxgVUpk7hNZt2Nr6qhA5GbY4TPVcTYwYpWWU8phJDZ1

Please let me know if you need anymore information

**Comment by nanos** [comment]
Hi @SiskoUrso ,

This is because you have supplied as string `"0"` rather than an integer `0` for `backfill-mentioned-users`:

https://github.com/SiskoUrso/FediFetcher/blob/83c82366c066dfeeeb418fc37ed8fea81b2d7795/config.json#L6

**Comment by SiskoUrso** [comment]
Thanks for the reply @nanos , oops I didn't even notice that when setting up, fixed it up and ran through it without issues. 

Thank you for taking a look.
