### ISSUE TITLE
How to use on-done, on-start, on-fail with secret URLs?

### ISSUE THREAD

**Issue by jaytay79** [nanos/FediFetcher#57]
I'm using the GitHub Action and would like to use on-done etc. but I don't want the URLs to be visible in the config.json file. Is there any way of achieving this?

**Comment by nanos** [comment]
Unfortunately not. 

Also, keep in mind that your GitHub Action execution logs are public anyway, so the urls would show up in there anyway. 

If you don’t want those public, you’ll need to run the script via cron on your own server (or in a container)

**Comment by jaytay79** [comment]
I was thinking something along the lines of how the access-token is handled... I'm not an expert when it comes to Actions but presumably I could create some new Repository secrets and then update get_context.yml to use them?

**Comment by nanos** [comment]
Whilst that is certainly technically possible, I've just moved away from supplying options in this way.

If you wanted to make some changes in your own fork to support that:

1) Add them a Action Secrets
2) Adjust the [.github/workflows/get_context.yml](https://github.com/nanos/FediFetcher/blob/93d5b503af92ec92a5891b55105ce6270efb82d6/.github/workflows/get_context.yml#L33C44-L33C44) file on line 33 to pass on the options as flags. Something along the lines of `--on-done=${{ secrets.ON_DONE }}` etc
