### ISSUE TITLE
Enhancement: Report version number in "Starting" message

### ISSUE THREAD

**Issue by PinballsWizard** [nanos/FediFetcher#58]
Can FediFetcher report its version number/git hash when starting so that can be logged?  I'm running locally and it'd be a nice way to verify the correct version is running.

**Comment by nanos** [comment]
I like the idea, because someone asked me how to figure out which version they are on the other day!

Implemented 👍

**Comment by nanos** [comment]
I have reverted this for now. See discussion in #70 for the reason behind this. 

In the mean time, if you want to check whether you are on the latest version locally run  `git fetch && git status` that should tell you what you need to know.
