### ISSUE TITLE
Running container with docker compose does not accept configuration from environment file

### ISSUE THREAD

**Issue by politas** [nanos/FediFetcher#62]
Putting command line options in as environment variables and launching using docker-compose always returns an error:

`You must supply at least a server name and an access token`

Docker documentation seems to say that the two methods should be identical. Is Fedifetcher reading from environment variables?

**Comment by nanos** [comment]
No, FediFetcher doesn’t read configuration options from environment variables when run in docker (don’t think it ever has - that was only ever possible for GitHub Action). 

Can you tell me where in the documentation you got that from? I’d like to clarify this.

**Comment by politas** [comment]
No, I think I may have been misreading the Docker documentation. I've just figured out that I can embed the command line arguments in my docker-compose.yml file with:
`command:
  - "--server=example.com"
  - "--access-token=longstringoflettersandnumbers
  ...`

It would be better if the code could check for environment variables to use, though. I might throw together a PR if it would be welcomed?

**Comment by nanos** [comment]
I'm not sure I want to add support of reading from environment variables back in: As I said, I just removed this for GitHub Actions (which admittedly work quite differently), because it was really confusing. 

You could create a json file with your configuration options instead?

**Comment by politas** [comment]
And then use it with the -c option? I'll give that a go. I might try running it as an entirely separate application; it seems to be having problems running as part of the Mastodon app.
