### ISSUE TITLE
Running in docker container errors adding url

### ISSUE THREAD

**Issue by politas** [nanos/FediFetcher#65]
The output I'm getting is full of Read Timeout errors:

`Error adding url https://my.server/api/v2/search?q=https://some.mastodon.instance/@randomuser/110750424011345796&resolve=true&limit=1 to server my.server. Exception: HTTPSConnectionPool(host='my.server', port=443): Read timed out. (read timeout=5)`

I get lots of successful `Added context url` messages, so it appears it's talking to the server. Is this expected behaviour?

**Comment by politas** [comment]
Ah, after leaving it running for a while, I'm now starting to get some messages like: `Added 44 new context toots (with 11 failures)` So I think that's more what I should be seeing?

**Comment by nanos** [comment]
You can use the `http-timeout` option to increase the timeout, if your instance is a bit slow to respond.

**Comment by politas** [comment]
Increasing `http-timeout` to 10  has it running without errors that aren't explained by trying to parse data from lemmy or peertube servers. Thanks!
