### ISSUE TITLE
403 on keep alive step?

### ISSUE THREAD

**Issue by quicoto** [nanos/FediFetcher#69]
I haven't changed anything from the repository but I suddently get 403 errors in the Keek worflow alive step

https://github.com/quicoto/mastodon-get-replies/actions/runs/5759223734/job/15613108531

Is there anything I can do from my side?

Thank you

**Comment by quicoto** [comment]
Just changed it, seems to work. It worked for months without this. Weird.

Thank you

**Comment by nanos** [comment]
Probably worked because it never actually needed to push anything. 

That part is only needed when you haven’t updated your fork for 60 days in a row. Quite possible that just never happened before.
