### ISSUE TITLE
Issues running FediFetcher over Misskey / Firefish

### ISSUE THREAD

**Issue by csolisr** [nanos/FediFetcher#81]
Misskey (and derivatives such as Firefish) have a certain compatibility with the Mastodon API; however, this seems to be incomplete. Upon testing FediFetcher against my personal Firefish server, I keep getting the following error several times:

> Error adding url https://social.example.net/api/v2/search?q=https://example.com/@user/110871785612416325&resolve=true&limit=1 to server social.example.net. Status code: 401

And finally:

> Added 0 posts for user user@example.com with 10 errors

**Comment by nanos** [comment]
unfortunately running FediFetcher against Firefish is not currently supported (see #67)
