### ISSUE TITLE
Node 16 actions deprecated

### ISSUE THREAD

**Issue by lnlyssg** [nanos/FediFetcher#92]
FYI you will need to update the GitHub workflows to newer actions (where available) as per https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

I'm seeing the below message on a recent run:

`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-python@v4, dawidd6/action-download-artifact@v2.`

I believe all of these actions have newer versions that use Node 20

**Comment by nanos** [comment]
Thanks @lnlyssg !

Can you check this against branch `node-16-depracation`?

**Comment by lnlyssg** [comment]
I will but I have spotted that line 41 of https://github.com/nanos/FediFetcher/blob/node-16-depracation/.github/workflows/get_context.yml still has a reference to actions/checkout@v3. Does build-container.yaml also need some updates? I haven't looked at that one.

**Comment by nanos** [comment]
Thanks! Fixed line 41.

I will look into build-container as well.

**Comment by nanos** [comment]
done thanks

**Comment by lnlyssg** [comment]
I've tested and can confirm all is working OK with the updated actions.

**Comment by nanos** [comment]
Amazing. Thank you!
